# Generated by Django 3.0.7 on 2020-06-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Shop', '0003_auto_20200621_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Coffee_Shop.User'),
        ),
    ]
