# Generated by Django 3.0.7 on 2020-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Shop', '0005_auto_20200622_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='Ashwini', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='Patil', max_length=125),
            preserve_default=False,
        ),
    ]
