# Generated by Django 3.0.7 on 2020-06-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Shop', '0006_auto_20200622_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
    ]
